### ISSUE TITLE
最近CSDN掉落红包雨，可以屏蔽掉吗？

### ISSUE THREAD

**Issue by Sologala** [adlered/CSDNGreener#75]
> 加入 QQ 群 1042370453 可直接与作者沟通

**Comment by adlered** [comment]
等它活动结束吧，我的电脑怎么都不显示红包雨，难过

**Comment by CHN-STUDENT** [comment]
+1 无语了，我是学技术取经了，不是看他们越做越傻x的

**Comment by SublimeCT** [comment]
可以直接 
```css
#csdn-redpack {display: none !important;}
```

活动并未结束, 只是只在某个时间段显示, 可以 `debug` 那个 `redpack.js` [详见这个回答](https://www.zhihu.com/question/429646314/answer/1568225894)
